# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Dhanraj Padmashali'
tagline:          'Personal Website'
description:      'Founder @ QuestLabs,Inc. <br>Developer|Designer|Foodie|Photographer|Nerd|Member of The Justice League'
url:              http://dhanrajsp.me
baseurl:          /

author:
  name:           'Dhanraj Padmashali'
  url:            https://twitter.com/psygik

paginate:         5

gems: [jekyll-paginate,jekyll-gist]

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
