# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Dhanraj Padmashali'
tagline:          'Personal Website'
description:      'Founder @ <a href="http://questlabs.xyz">QuestLabs,Inc.</a> <br>Developer|Designer'
url:              http://dhanrajsp.me
baseurl:          /

author:
  name:           'Dhanraj Padmashali'
  url:            https://twitter.com/psygik

paginate:         5

gems: [jekyll-paginate,jekyll-gist]

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
